# Project-wide Gradle settings

# JVM
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Non-transitive R classes
android.nonTransitiveRClass=true

# Compose compiler reports (enable when profiling)
# kotlin.compose.compiler.report=true

# Parallel & caching
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
